name: Restful API Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run:  |  
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py makemigrations
        python manage.py migrate
    - name: Coverage report
      run:  |
        pip3 install coverage
        coverage run mysite_rebrand/manage.py test
        coverage report


# name: REST API
# on: [push, pull_request]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     services:
#       postgres:
#         image: postgres:10.8
#         env:
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: postgres
#           POSTGRES_DB: github_actions
#         ports:
#           - 5432:5432
#         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5  
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Python 3.9.7
#         uses: actions/setup-python@v1
#         with:
#           python-version: 3.9.7
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt